name: riverpod2_test_drive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation: ^2.3.5
  riverpod_lint: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  riverpod_generator: 


flutter:
  uses-material-design: true
